# Generated by Django 2.1.5 on 2019-01-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GaLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('type_of_lesson', models.CharField(max_length=200)),
                ('lesson_url', models.TextField()),
                ('date', models.CharField(max_length=50)),
            ],
        ),
    ]
